### ISSUE TITLE
Only localhost works

### ISSUE THREAD

**Issue by arda1984** [Alygnt/Clifty#21]
I didn't change the custom port nor did I change the redirect link
![image](https://user-images.githubusercontent.com/70358147/212727362-f43e7b59-40ef-4d23-a657-5c13e9ee7604.png)

**Comment by Alygnt** [comment]
Sorry for inconvenience, can i know what tunneling service you tried like ngrok or cloudflare or what?

**Comment by Alygnt** [comment]
I have fixed it now ngrok and cloudflare too works
