### ISSUE TITLE
OTP issue

### ISSUE THREAD

**Issue by p0l4rT** [Alygnt/Clifty#27]
When you select to use the OTP version the tool only take the redirect but not asking for OTP, just user and password and done, redirect...

**Comment by G4k3r** [comment]
same issue don't know if they will fix

**Comment by Alygnt** [comment]
@G4k3r Sure I will fix it. 
Currently, I am working on the 1.5 version update.
@p0l4rT and @G4k3r Can you please tell me on which site did you face this issue? So that I can fix it today itself

**Comment by p0l4rT** [comment]
I got the issue using the Instagram site

**Comment by Alygnt** [comment]
I have fixed it and also added few new features. Just give a star ⭐ to the repo
