### ISSUE TITLE
Camera tools not working

### ISSUE THREAD

**Issue by Pritamvaghela168** [Alygnt/Clifty#35]
Just faced no site download try again! But i download all of site which available on it.

**Comment by Alygnt** [comment]
Thank you so much for reporting the bug, I checked it and fixed it... NOW IT WORK'S PERFECT, No matter whether you downloaded all the sites or not, It will work fine...

**Comment by Alygnt** [comment]
And also please update the tool by using [ F ] command in home page then try the tool, If any issues let me know and If it works fine please give a star to this repository
