### ISSUE TITLE
Cloudflare not working 

### ISSUE THREAD

**Issue by cunactmail** [Alygnt/Clifty#40]
![Screenshot_20230508-085023_Termux](https://user-images.githubusercontent.com/132868240/236729841-30c4b6c4-77dd-439b-bf6a-d9098dd45390.jpg)

error in generating link

**Comment by blazer-onyx** [comment]
same

**Comment by Bad-Boy2p** [comment]
me too I have the same problem

**Comment by Alygnt** [comment]
CLOUDFLARED FIXED!!
