### ISSUE TITLE
This Tool does nothing it claims to do

### ISSUE THREAD

**Issue by Chocolate-cockie** [Alygnt/Clifty#43]
Localxpose does not work, ngrok does not work,even localhost does not work 😅😅⚒

**Comment by Alygnt** [comment]
I am fixing Ngrok and cloudflared, and localhost must work, Check again properly

**Comment by Chocolate-cockie** [comment]
Fix localxpose too

**Comment by Toolsforlegends** [comment]
> I am fixing Ngrok and cloudflared, and localhost must work, Check again properly 

It only pulls my information and not the person I'm trying to get

**Comment by ElsonFabiano** [comment]
can i have a tutorial video for facebook phishing

**Comment by Alygnt** [comment]
NGROK FIXED!!
