### ISSUE TITLE
Unsupported package manager, Install packages manually.

### ISSUE THREAD

**Issue by TlochstaDev** [Alygnt/Clifty#53]
Unsupported package manager, Install packages manually.
when i am using this on windows 11 and using GIT Bash it gives me this error how do i install packages manually im dumb

**Comment by Alygnt** [comment]
You can install manually, But as your a starter I would not recommend it as its a long process. Therefore use any other terminals like ubuntu, kali, termux etc. If you don't have access to such platforms, you can use **[Google Cloud shell](https://shell.cloud.google.com/?pli=1&show=ide,terminal)** as its free and doesn't require installation. All you need for it is a proper internet connection. 

Thanks and Regards,
Alygnt.
