### ISSUE TITLE
my site is not working

### ISSUE THREAD

**Issue by Snopboy9999** [Alygnt/Clifty#82]
"The requested resource /index.html was not found on this server". this is what i get when i open the site after forwarding port using localhost 8080

**Comment by aryansingh100aryan** [comment]
> Can I know for which site you tried?
> 

Sir, ngrok and Cloudflared server not working.. Plz fix this ..

**Comment by Alygnt** [comment]
Sorry for the inconvenience caused. Thanks for reporting the error.
This error is FIXED Now 🥳. Please update and try running the tool again. 
Please give a star to repo.
