### ISSUE TITLE
error after user logging in 

### ISSUE THREAD

**Issue by P4BLO95** [Alygnt/Clifty#86]
![error](https://github.com/Alygnt/Clifty/assets/140578783/e653ce2e-60a2-42d8-a7d0-89bdfe6f95bb)

**Comment by Alygnt** [comment]
Can I know which site you tried

**Comment by P4BLO95** [comment]
steam

**Comment by Alygnt** [comment]
Sorry for the inconvenience caused. Thanks for reporting the error.
This error is FIXED Now 🥳. Please update and try running the tool again. 
Please give a star to repo.
