### ISSUE TITLE
error in generating the link 

### ISSUE THREAD

**Issue by P4BLO95** [Alygnt/Clifty#87]
![error in generating the link](https://github.com/Alygnt/Clifty/assets/140578783/b8a47ba1-ef51-4891-8ad2-bd90537bb5ca)

Kindly fix this issue thankyou <3

**Comment by P4BLO95** [comment]
bump

**Comment by Alygnt** [comment]
Working on it...

**Comment by Alygnt** [comment]
NGROK FIXED!!
