### ISSUE TITLE
generation of links fixed but some sites fail to redirect

### ISSUE THREAD

**Issue by Snopboy9999** [Alygnt/Clifty#92]
everything works perfectly fine now with the generation of the link. I'm glad you fixed the errors. but there's one more thing, links generate perfectly fine now but some links fail to redirect to the original site. i tried with paypal and it's failing to redirect to the paypal site login page...

instagram redirects fine but paypal, snapchat and a couple of others fail to redirect. It gives me the 404 error when trying to redirect

will be glad if you can help me out

**Comment by Alygnt** [comment]
I checked it, I found the error. The bug will be fixed soon... STAY TUNED.

Thanks for reporting
please give a star to the repo

**Comment by Alygnt** [comment]
BUG FIXED!!
