### ISSUE TITLE
Link's are down for some sites/ masking url doesn't work ..

### ISSUE THREAD

**Issue by profesionalleet1337** [Alygnt/Clifty#93]
The Tool is good, but from some days, the link of some sites didn't work, and for bad the masker also didn't work .. Could be fixed/ updated ?

**Comment by Alygnt** [comment]
Yeah, Working on it... The api servers got some issues.. I will check them and fix it soon

**Comment by profesionalleet1337** [comment]
Yeah, thank's for fast response ! I noticed that all the tool working with option to "mask" are not working , as you said the problem with the api, maybe .. So there is no working masking instrument that work properly  at the moment ,right ?

**Comment by Alygnt** [comment]
Yeah, I am going to check for alternatives and check whether the shortening service made any changes to API and update code...

**Comment by Alygnt** [comment]
> Yeah, thank's for fast response ! I noticed that all the tool working with option to "mask" are not working , as you said the problem with the api, maybe .. So there is no working masking instrument that work properly at the moment ,right ?

But if you need, I can add mask link feature for normal long URL ( ngrok, clouflared, loclaxpose, serveo). Let me know if you need it...

**Comment by profesionalleet1337** [comment]
> > Yeah, thank's for fast response ! I noticed that all the tool working with option to "mask" are not working , as you said the problem with the api, maybe .. So there is no working masking instrument that work properly at the moment ,right ?
> 
> But if you need, I can add mask link feature for normal long URL ( ngrok, clouflared, loclaxpose, serveo). Let me know if you need it...



Yes, would be great to have that bonus option .. however a big part of the whole "procedure" is to be as well hidden as possible so it would be extremely useful for everyone I think ?

**Comment by Alygnt** [comment]
Sure I will add it soon. but I want to inform you of one thing before itself, that is adding a mask to the long link will make the link much longer.
And speaking about link shortening, most of APIs are shut down... I wasn't able to find a good alternative either. Let me know if you find some link-shortening service API without authentication.

**Comment by profesionalleet1337** [comment]
> Sure I will add it soon. but I want to inform you of one thing before itself, that is adding a mask to the long link will make the link much longer. And speaking about link shortening, most of APIs are shut down... I wasn't able to find a good alternative either. Let me know if you find some link-shortening service API without authentication.

Yes, that's exactly what I wrote about. For about a month, no phishing tool with a built-in mask - is functioning properly. I guess it's all based on an API principle and it's possible instagram banned it , I have no other idea. I also searched a lot, but actually there are like 2-3 "public" masking tools in guthub,  that apparently work on the same principle.. I will keep searching, if something pops up I will write. If you manage to find some too, you can keep us posted !
(Do you have a discord or telegram where we can exchange information ? )

**Comment by Alygnt** [comment]
Sure, and thanks for helping me out to upgrade this tool. The link-shorten APIs are down because of their lack of maintenance and other stuff, Instagram can't ban them... As far as I most of the API link-shortening services are down. I am surprised because I kept 5 shortening options and I never expected all 5 services to go down. For now, I will add the link mask feature to the long URL and suspend the shortening link option (that's the only choice). Let's look for a better option till then. 

Update 1.5 will be rolled out soon.

STAY TUNED!!

My Instagram username - mralygnt
My Twitter username - alygnt
My discord username - alygnt
Facebook page : https://www.facebook.com/profile.php?id=61552517980412

**Comment by profesionalleet1337** [comment]
Thanks for the reply and for the product support ! Hopefully you can come up with a compromise and upgrade the tool. We will wait for the update !

**Comment by Alygnt** [comment]
AN UPDATE REGARDING LINK SHORTENING :
In the previous version I have included 3 link shortening APIs, they are,
1. is.gd
2. Shortcode
3. TinyURL

Now after few research I found that the Shortcode server is completely down and in the case of is.gd and TinyURL they are blocking the links from ngrok, cloudflared, localxpose, serveo etc.... 

This was the reason link shortening tools were not working

**Comment by profesionalleet1337** [comment]
> AN UPDATE REGARDING LINK SHORTENING : In the previous version I have included 3 link shortening APIs, they are,
> 
> 1. is.gd
> 2. Shortcode
> 3. TinyURL
> 
> Now after few research I found that the Shortcode server is completely down and in the case of is.gd and TinyURL they are blocking the links from ngrok, cloudflared, localxpose, serveo etc....
> 
> This was the reason link shortening tools were not working

Thanks for the inclusion ! Yes I understand your point but what is the solution ? The mask is quite an important part of the process, and it would be nice to have it.
-> Now I tried to do a test with generating pages like facebook / instagram, but for both options it gives errors, does not generate any links, no matter which "provider" I choose - whether it is cloudflare or localhost ..
( With adobe successfully made a page ), but the most common use like facebook, instagram, messenger, gmail maybe you need to update them ? ( messenger and gmail I have not tested, just guessing )

**Comment by Alygnt** [comment]
Hey, As I promised... Now the mask feature works for all links...

I understand your issue... You can just visit shortened link services online websites like Bitly, TinyURL, etc... 

If all your issues are fixed can I close this issue with your kind permission?

**Comment by profesionalleet1337** [comment]
> Hey, As I promised... Now the mask feature works for all links...
> 
> I understand your issue... You can just visit shortened link services online websites like Bitly, TinyURL, etc...
> 
> If all your issues are fixed can I close this issue with your kind permission?

I have write you on discord : )

**Comment by Alygnt** [comment]
Sure, I will reply ASAP!! For now I am closing this issue

**Comment by profesionalleet1337** [comment]
@Alygnt Could u updated, bro ? Having some problem's , if you noticed..

**Comment by Alygnt** [comment]
@profesionalleet1337 Please explain your issue

**Comment by profesionalleet1337** [comment]
> @profesionalleet1337 Please explain your issue

Again masking option .. No is.gd.
I mean .. If the generated sites is this https://xxxx.com@xx-xx-xx-xx.trycloudflare.com , the mask its looks like this - >  https://xxxxx.com.xxx-xxxx-xxx-xxx.trycloudflare.com . I mean, nothing is changing, only going with more letter's ..

**Comment by Alygnt** [comment]
Yeah I get it, Currently I am working in next update 1.6 in that I am happy to tell u that clifty will have its own link shortene from Clifty v1.6 . Yeah that right... From next update there won't be any 3rd party link shortener..

**Comment by profesionalleet1337** [comment]
> Yeah I get it, Currently I am working in next update 1.6 in that I am happy to tell u that clifty will have its own link shortener from Clifty v1.6 . Yeah that right... From next update there won't be any 3rd party link shortener..

Really ? Glad to hear that! Sounds good , and when to expect the new- update?

**Comment by profesionalleet1337** [comment]
@Alygnt Hello, bro ! What's up ? Any new ?
